# Generated by Django 4.2 on 2023-05-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(blank=True, null=True)),
                ("Close", models.FloatField(blank=True, null=True, verbose_name="終値")),
                ("High", models.FloatField(blank=True, null=True, verbose_name="高値")),
                ("Low", models.FloatField(blank=True, null=True, verbose_name="安値")),
                ("Open", models.FloatField(blank=True, null=True, verbose_name="始値")),
                (
                    "Volume",
                    models.FloatField(blank=True, null=True, verbose_name="出来高"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.brands"
                    ),
                ),
            ],
        ),
    ]
