# Generated by Django 4.2 on 2023-05-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_trades"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="is_holding",
            field=models.BooleanField(blank=True, null=True, verbose_name="保有"),
        ),
        migrations.AddField(
            model_name="brands",
            name="is_watching",
            field=models.BooleanField(blank=True, null=True, verbose_name="監視"),
        ),
    ]
