# Generated by Django 4.2 on 2023-05-07 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_brands_is_holding_brands_is_watching"),
    ]

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("trend", models.CharField(max_length=5)),
                ("judge", models.TextField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.brands"
                    ),
                ),
            ],
        ),
    ]
